Tugule/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from  django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugulenga.urls',namespace='tugule')),
    path('products/',include('products.urls',namespace='products'))


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
app_name="products"
urlpatterns=[
    path('',views.home,name="home"),
    
    path('cart/',views.cart,name="cart"),
    path('delete_order/<str:product_id>',views.deleteOrder,name="delete_order"),
    path('category/<str:category_id>', views.products, name='category'),
    path('update_item/', views.update_item, name='update_item'),
    path('checkout/',views.checkout,name="checkout"),
    path('checkout-order/',views.checkout_order,name='checkout-order')
  
]

tugulenga/urls.py
from django.urls import path
from . import views
app_name="tugule"
urlpatterns=[
    path('',views.home,name="home"),
    path('signup/',views.signup,name="signup"),
    path('login/',views.loginPage,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('add_product/', views.add_product, name="add_product"),
    path('profile/', views.profileForm, name= "profile"),
    path('business-profile/', views.business_profile, name= "business-profile"),
    path('business_form/', views.create_businesss, name= "create_business"),
    path('edit-business/', views.edit_business, name= "edit_business"),
    path('edit-product/<str:product_id>', views.edit_product, name="edit_product"),
    path('edit_profile/', views.edit_profile, name= "edit_profile"), 
    path('product_details/<str:product_id>', views.product_detail, name="product_details"),
    path('ratings/<int:product_id>', views.post_rating,name="post_rating"),
    path('search/', views.search, name='search'),
]

tugulenga/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
import math
# Creating  models here.
class Profile (models.Model):
    user = models.OneToOneField(User,null=True, on_delete=models.CASCADE) # One to one relationship with the User model.
    # image = models.ImageField(default='avatar.png', upload_to= 'profile/', blank=True)
    contact = models.CharField(max_length = 50, blank = True, null = True,)
    name = models.CharField(max_length = 200, blank = True, default="user")

  
    

    def __str__(self):
        return f'{self.user.username} Profile'
    
    #save the profile
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
        # img = Image.open(self.image.path)
        # if img.height > 300 or img.width > 300:
        #     output_size =(300,300)
        #     img.thumbnail(output_size)
        #     img.save (self.image.path)

    

#created this model for database table for the the business account
class Business_account(models.Model):

    owner= models.OneToOneField(User,on_delete= models.CASCADE, blank = True, null = True)
    name = models.CharField(max_length = 100)
    phone = models.CharField(max_length =20)
    email = models.EmailField()
    location = models.CharField(max_length = 255)
    description = models.TextField()
    logo = models.ImageField(upload_to='Logos/', null= True, blank=True)
    
    

    def __str__(self):
        return self.name
    
class Category(models.Model):
    name= models.CharField(max_length=50)
    image =  models.ImageField( upload_to="Categories/", blank =True,null=True)

    def __str__(self):
        return self.name
    

#created this model for database table for the the Products  
class Product(models.Model):
        
        business_account= models.ForeignKey(Business_account, on_delete=models.CASCADE, null=True, blank=True )
        image =  models.ImageField( upload_to="Products/", blank =True)
        category=models.ForeignKey(Category,max_length=20, null=True,on_delete=models.CASCADE,blank=True)
        name = models.CharField(max_length=200, null=True)
        price = models.FloatField()
        
        def __str__(self):
            return self.name


    
#created this model for database table for the Order   
class Order(models.Model):
    customer = models.ForeignKey(User,on_delete= models.CASCADE, null=True,blank=True)
    date_ordered = models.DateTimeField(auto_now_add= True)
    complete = models.BooleanField(default=False, null=True,blank =False)
    

    def __str__(self):
        return str(self.id)
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


#created this model for database table for ordering items   
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank = True, null=True)
    customer = models.ForeignKey(Profile,on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name 
    @property
    def get_total(self):
        total = self.product.price *self.quantity
        return total



class Rating(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='ratings')
    value=models.IntegerField()

    def __str__(self) -> str:
        return str(self.value)
    
    @property
    def get_value(self):
        return self.value

class Review(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='review')
    text =models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    


    





     
    

tugulenga/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import  UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import *



class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['image','category','name','price']

class Business_accountForm(ModelForm):
    class Meta:
        model = Business_account
        fields = '__all__' 
        exclude= ['owner']


class OrderForm(ModelForm):
    class Meta:
        model=Order
        fields = '__all__'  

class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

class  CreateUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username', 'email','password1', 'password2']

class ProfileForm(ModelForm):
    class  Meta:
         model=Profile
         #name=forms.CharField(max_length=200, widget=forms.TextInput({"placeholder": "Your Username"}))
         fields=['contact','name']
         widgets={"name":forms.Textarea(attrs={'placeholder':'Username'})}

tugulenga/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib.auth.models import Group
from django.contrib.auth.forms import  UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login ,logout
from django.contrib import messages
from .decorators import unauthenticated_user
from .models import *
from .forms import *
from django.db.models import Q


# Create your views here.
def home(request):
    
    return render(request,'tugulenga/index.html')

# Decorator to ensure that only unauthenticated users can access this view
@unauthenticated_user
def signup(request):
    # Create an instance of the CreateUserForm
    form = CreateUserForm()
    
    # Check if the request method is POST (i.e., the form has been submitted)
    if request.method == 'POST':
        # Create a new instance of the CreateUserForm, populated with the submitted data
        form = CreateUserForm(data=request.POST)
        
        # Check if the form is valid (i.e., all fields have been filled in correctly)
        if form.is_valid():
            # Save the form data to the database
            form.save()
            
            # Get the username from the form data
            user = form.cleaned_data.get('username')
            
            # Display a success message to the user
            messages.success(request, 'Account was created for ' +user)
            
            # Redirect the user to the login page
            return redirect('tugule:login')
    
    # Create a context dictionary to pass to the template
    context = {"form": form}
    
    # Render the signup HTML template, passing the context dictionary
    return render(request, "tugulenga/signup.html", context)
# Decorator to ensure that only unauthenticated users can access this view
@unauthenticated_user
def loginPage(request):
   
    # Check if the request method is POST (i.e., the user has submitted the login form)
    if request.method == 'POST':
        
        # Get the username and password from the form data
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        # Authenticate the user using the provided username and password
        user = authenticate(request, username=username, password=password)
        
        # If the user is authenticated, log them in and redirect them to the appropriate page
        if user is not None:
            login(request, user)
            try:
                # Check if the user is a business account owner
                business = Business_account.objects.get(owner=request.user)
                
                # Display a success message and redirect the user to the business profile page
                messages.success(request, "Logged In")
                return redirect('tugule:business-profile')
            except:
                # If the user is not a business account owner, redirect them to the home page
                messages.success(request, "Logged In")
                return redirect('products:home')
        else:
            # If the authentication fails, display an error message
            messages.info(request, 'Username or Password is incorrect')
        
    # Render the login HTML template
    return render(request, 'tugulenga/login.html')

# Function to log out the user
def logoutUser(request):
    # Log out the user
    logout(request)
    
    # Display a success message
    messages.success(request, "Logged out")
    
    # Redirect the user to the home page
    return redirect('tugule:home')

  
def add_product(request):
    # Get the business account associated with the current user
    business_account = Business_account.objects.get(owner=request.user)
    
    # Check if the request method is POST (i.e., the form has been submitted)
    if request.method == 'POST':
        # Create a new instance of the ProductForm, populated with the submitted data
        form = ProductForm(request.POST, request.FILES)
        
        # Check if the form is valid (i.e., all fields have been filled in correctly)
        if form.is_valid():
            # Extract the image, category, name, price, and other fields from the form data
            image = form.cleaned_data['image']
            category = form.cleaned_data['category']
            name = form.cleaned_data['name']
            price = form.cleaned_data['price']
            
            # Create a new Product instance with the extracted data
            product = Product.objects.create(
                business_account=business_account,
                image=image,
                name=name,
                price=price,
                category=category,
            )
            
            # Save the product to the database
            product.save()
            
            # Redirect the user to the home page
            return redirect('tugule:business-profile')
    
    # If the request method is not POST (i.e., the form has not been submitted), create a new instance of the ProductForm
    else:
        form = ProductForm()
    
    # Render the add_product HTML template, passing the form instance as a variable
    return render(request, 'tugulenga/add_product.html', {'form': form})

def create_businesss(request):
    # Check if the request method is POST (i.e., the form has been submitted)
    if request.method == 'POST':
        # Create a new instance of the Business_accountForm, populated with the submitted data
        form = Business_accountForm(request.POST, request.FILES)
        
        # Check if the form is valid (i.e., all fields have been filled in correctly)
        if form.is_valid():
            # Create a new Business_account instance with the submitted data, but do not save it yet
            business = form.save(commit=False)
            
            # Set the owner of the business account to the current user
            business.owner = request.user
            
            # Save the business account to the database
            business.save()
            
            # Redirect the user to the business profile page
            return redirect('tugule:business-profile')
    
    # If the request method is not POST (i.e., the form has not been submitted), create a new instance of the Business_accountForm
    else:
        form = Business_accountForm()
    
    # Render the business-form HTML template, passing the form instance as a variable
    return render(request, 'tugulenga/business-form.html', {'form': form})

def edit_business(request):
    # Get the business account associated with the current user
    business = Business_account.objects.get(owner=request.user)
    
    # Check if the request method is POST (i.e., the form has been submitted)
    if request.method == 'POST':
        # Create a new instance of the Business_accountForm, populated with the submitted data and the existing business account instance
        form = Business_accountForm(request.POST, request.FILES, instance=business)
        
        # Check if the form is valid (i.e., all fields have been filled in correctly)
        if form.is_valid():
            # Save the updated business account to the database
            form.save()
            
            # Redirect the user to the business profile page
            return redirect('tugule:business-profile')
        
    # If the request method is not POST (i.e., the form has not been submitted), create a new instance of the Business_accountForm with the existing business account instance
    else:
        form = Business_accountForm(instance=business)
    
    # Create a context dictionary to pass to the template
    context = {'form': form}
    
    # Render the edit-business HTML template, passing the form instance as a variable
    return render(request, 'tugulenga/edit-business.html', context)
def edit_product(request, product_id):
    # Get the product instance with the specified ID
    product = Product.objects.get(id=product_id)
    
    # Check if the request method is POST (i.e., the form has been submitted)
    if request.method == 'POST':
        # Create a new instance of the ProductForm, populated with the submitted data and the existing product instance
        form = ProductForm(request.POST, request.FILES, instance=product)
        
        # Check if the form is valid (i.e., all fields have been filled in correctly)
        if form.is_valid():
            # Save the updated product to the database
            form.save()
            
            # Redirect the user to the business profile page
            return redirect('tugule:business-profile')
    
    # If the request method is not POST (i.e., the form has not been submitted), create a new instance of the ProductForm with the existing product instance
    else:
        form = ProductForm(instance=product)
    
    # Create a context dictionary to pass to the template
    context = {'form': form, "product": product}
    
    # Render the edit-product HTML template, passing the form instance and product instance as variables
    return render(request, 'tugulenga/edit-product.html', context)

    
def profileForm(request):
    # Get the profile instance associated with the current user
    profile = Profile.objects.get(user=request.user)
    
    # Create a context dictionary to pass to the template
    context = {"profile": profile}
    
    # Render the profile HTML template, passing the profile instance as a variable
    return render(request, 'tugulenga/profile.html', context)

def business_profile(request):
    # Get the business account instance associated with the current user
    business = Business_account.objects.get(owner=request.user)
    
    # Get all the product instances associated with the business account
    products = Product.objects.filter(business_account=business)
    
    # Get all the order item instances
    orderitems = OrderItem.objects.all()
    

tugulenga/templates/tugulenga/add_product.html
{%extends 'tugulenga/base.html' %}
{% block content%}
<style>
       body {
            font-family: Arial, sans-serif;
            background-color: rgb(179, 178, 182);
        }

</style>
<form class="auth" enctype="multipart/form-data" action="{% url 'tugule:add_product' %}" method="POST">
    {{form}} {% csrf_token %}
    <button class="auth btn btn-sm"style=" border-radius: 10px; background: teal; border:4px solid white ; color: white;" type="submit" >Add</button>
</form>

{% endblock %}

tugulenga/templates/tugulenga/business-form.html
{% extends 'tugulenga/base.html' %} 
{% load bootstrap5 %}
{% block content %}
<head>
    <style>
        body{
            background-color:rgb(179, 178, 182);
        }
    </style>
</head>
<h2>Create Business</h2>
<form method="POST" enctype="multipart/form-data" class="auth">
    {%csrf_token%}
    {%bootstrap_form form layout='horizontal'%}
    <button class="auth btn btn-sm" style="background-color:rgb(255, 0, 64); color: rgb(2, 24, 17);" type="submit">Create Business</button>
</form>
{%endblock%}

tugulenga/templates/tugulenga/edit-product.html
{%extends 'tugulenga/base.html' %}
{% block content%}
<form class="auth" enctype="multipart/form-data" action="{% url 'tugule:edit_product' product.id %}" method="POST">
    {{form}} {% csrf_token %}
    <button class="auth" type="submit">Edit</button>
</form>

{% endblock %}

tugulenga/templates/tugulenga/edit_profile.html
{% extends 'tugulenga/base.html' %} 
{% load bootstrap5 %}
{% block content %}
<style>
    body {
         font-family: Arial, sans-serif;
         background-color: rgb(179, 178, 182);
     }

</style>

<h2>Edit Profile</h2>
<form method="POST" action="{% url 'tugule:edit_profile' %}" enctype="multipart/form-data" class="auth">
    {%csrf_token%}
    {%bootstrap_form form layout='horizontal'%}
    <button class="auth btn btn-sm"style=" border-radius: 10px; height: 40px;width: 150px; background: teal; border:4px solid white ; color: white;" type="submit">Edit</button>
    
</form>
{%endblock%}

tugulenga/templates/tugulenga/index.html
{%load static%}
{%load bootstrap5%}
{% bootstrap_css %}
{%bootstrap_javascript%}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Tugule</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" type="image/png" href="https://image.ibb.co/fOur3b/favicon.png"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel='stylesheet' href='https://cdn.rawgit.com/filipelinhares/ress/master/dist/ress.min.css'><link rel="stylesheet" href="{% static 'css/slide.css' %}">
<meta name="theme-color" content="#3a9fff">
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css'>
<link rel="stylesheet" href="{%static 'css/stylez.css'%}">



<!-- partial:index.partial.html -->

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" type="image/x-icon" href="{%static 'images/logo.jpg'%}"/>
<meta name="theme-color" content="#1885ed">
<title>Tugule- Homepage</title>
</head>

<body>
  
  
  <header class="header">
    <div class="container header__container">
      <div class="header__logo"><img class="header__img" src="{%static 'images/logo.png'%}"height=70px style="border-radius: 100%;"> <h1 class="header__title">Tugule<span class="header__light"></span></h1></div> 
      <nav class="navbar bg-body-tertiary fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Dashboard</a>
    <button class="navbar-toggler " type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <svg xmlns="http://www.w3.org/2000/svg" height="50" width="50" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#050e1f" d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/></svg>

    </button>
    <div class="container-fluid">
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Tugule</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body h-100">
          {% if user.is_authenticated and not request.user.business_account %}
          <form action="{%url 'tugule:search'%}" method="GET" class="d-flex" role="search">
            <input class="form-control me-2" type="search" name="search" placeholder="Search Products" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
          {% endif %}
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 w-100">
            
            {% if not user.is_authenticated %}
            <li class="nav-item"><a href="{%url 'tugule:signup'%}" class="nav-link w-50 btn btn--white">Register now!</a></li>
            <br>
            <li class="nav-item"><a href="{%url 'tugule:login'%}" class="nav-link btn btn--white w-50">Log In →</a></li>
            <be></be>
            {%else%}
            <li class="nav-item"><a href="{%url 'tugule:logout'%}" class="nav-link btn btn-danger btn-lg p-4 w-50" style="background-color:red; color:black;">Log out</a></li>
            <li class="nav-item">
              <a class="nav-link btn btn--white w-50 mb-4 mt-4" style=color:black href="{%url 'tugule:profile'%}">Profile</a>
            </li>
            
            {%if request.user.business_account  %}
            <li class="nav-item">
              <a class="nav-link btn btn--white w-50"style=color:black href="{%url 'tugule:business-profile'%}">Business Profile</a>
            </li>
            {%else%}
            <li class="nav-item btn btn--white w-50 p-0"><a href="{%url 'products:home'%}" class="nav-link">Product Categories</a></li>
            <li class="nav-item"><a href="{%url 'products:cart'%}" class="nav-link"><svg xmlns="http://www.w3.org/2000/svg" width="36" height="26" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
              <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
            </svg></a></li>
            
            {% endif %}
            {% endif %}
            
            
            
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <div class="header__menu w-100">
    <nav id="navbar" class="header__nav collapse">
      <ul class="header__elenco w-100">
        <div class="d-flex flex-row" style="width: 200px;">
          <li class="header__el"><a href="{%url 'tugule:home'%}" class="header__link">Dashboard</a></li>
        </div>
      </ul>
      <form class="d-flex mt-3" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</div>
</nav>     
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
      
    </nav>
  </div>
</div>

</header>

<div class="sect sect--padding-top">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="site">
          <h1 class="site__title"></h1>
          <h2 class="site__title">Where Users Meet Businesses in a Click!</h2>
          
          
    
      
     {% include 'tugulenga/slide.html' %}
    </div>
    </div>
    </div>
  </div>
</div>




<div class="sect sect--violet ">
  <img src="https://image.ibb.co/fWyVtb/path3762.png" class="career-img">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p class="career_title">Tugule is a commercial online web platform designed to provide users with a seamless shopping experience. Whether you are a customer looking for quality products or a seller aiming to showcase your merchandise. Tugule offers a platform that meets your needs.</p>
        
        
      </div>
    </div>
  </div>
  
</div>




<!-- partial -->
 
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.2/js/swiper.jquery.min.js'></script>
<script  src="{%static 'js/script.js'%}"></script>
<script src="{% static 'js/slides.js' %}"></script>
</body>
</html>

tugulenga/templates/tugulenga/profile.html
{% extends 'tugulenga/base.html' %} 
{% load bootstrap5 %}
{% block content %}
<br>
<head>
    <style>
        body{
            background-color:rgb(179, 178, 182);
        }
    </style>
</head>
<div class="container pb-4">
    <div class="card border-light mb-3" style="max-width: 28rem;background-color:teal;">
        <div class="card-header bg-transparent border-light"> <h4>
                            
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-person-square" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1v-1c0-1-1-4-6-4s-6 3-6 4v1a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>
            </svg>
            {% if profile.name == 'user' %}
      {{request.user.username}}
      {% else %}
      {{profile.name}}
            {% endif %}
        </h4></div>
        <div class="card-body ">
          <h5 class="card-title"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"width="26" height="26"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z"/></svg>
            {{request.user.email}}</h5>
          <p class="card-text"style="color:black">
             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"  class="bi bi-telephone-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
            </svg>  {{profile.contact}}</p>
        </div>
        <div class="card-footer bg-transparent border-light"><a class="btn btn-dark" href="{%url 'tugule:edit_profile' %}">Edit</a></div>
      </div>
   
            
        </div>
    </div>
</div>
{%endblock%}
</body>