Tugule/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from  django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugulenga.urls',namespace='tugule')),
    path('products/',include('products.urls',namespace='products'))


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
app_name="products"
urlpatterns=[
    path('',views.home,name="home"),
    
    path('cart/',views.cart,name="cart"),
    path('delete_order/<str:product_id>',views.deleteOrder,name="delete_order"),
    path('category/<str:category_id>', views.products, name='category'),
    path('update_item/', views.update_item, name='update_item'),
    path('checkout/',views.checkout,name="checkout"),
    path('checkout-order/',views.checkout_order,name='checkout-order')
  
]

tugulenga/urls.py
from django.urls import path
from . import views
app_name="tugule"
urlpatterns=[
    path('',views.home,name="home"),
    path('signup/',views.signup,name="signup"),
    path('login/',views.loginPage,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('add_product/', views.add_product, name="add_product"),
    path('profile/', views.profileForm, name= "profile"),
    path('business-profile/', views.business_profile, name= "business-profile"),
    path('business_form/', views.create_businesss, name= "create_business"),
    path('edit-business/', views.edit_business, name= "edit_business"),
    path('edit-product/<str:product_id>', views.edit_product, name="edit_product"),
    path('edit_profile/', views.edit_profile, name= "edit_profile"), 
    path('product_details/<str:product_id>', views.product_detail, name="product_details"),
    path('ratings/<int:product_id>', views.post_rating,name="post_rating"),
    path('search/', views.search, name='search'),
]

products/models.py
from django.db import models

# Create your models here.

products/views.py
from django.shortcuts import render,redirect
from tugulenga.models import *
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json
from django.contrib import messages


#views to create cart items
# Function to display the contents of a user's shopping cart
@login_required(login_url='tugule:login')
def cart(request):
    # Check if the user is authenticated
    if request.user.is_authenticated:
        # Retrieve the current order for the user
        order, created = Order.objects.get_or_create(customer=request.user, complete = False)
        # Retrieve all the items in the order
        items = order.orderitem_set.all()
    else:    
        # If the user is not authenticated, set the items to an empty list
        items=[]
        # Set the order to a dictionary with two keys: get_cart_total and get_cart_items, both set to 0
        order ={'get_cart_items':0, 'get_cart_total':0}
    # Create a dictionary called context that contains the items and order variables
    context = {'items':items, 
               'order':order}
    # Return an HTTP response that renders the cart.html template and passes the context dictionary to the template
    return render(request,"products/cart.html", context)
@login_required(login_url='tugule:login')
def checkout(request):
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(customer=request.user, complete = False)
        items = order.orderitem_set.all()
    else:    
        items=[]
        order ={'get_cart_total':0,'get_cart_items':0}
    context = {'items':items, 
               'order':order}
    return render(request,"products/checkout.html", context)

def update_item(request):
    data = json.loads(request.body)
    productId = data['product_id']
    action = data['action']

    customer = request.user
    product = Product.objects.get(id=productId)
    order,created = Order.objects.get_or_create(customer=customer, complete=False)
    order_item,created = OrderItem.objects.get_or_create(order=order, product=product)
    if action == "add":
        order_item.quantity = (order_item.quantity+1)
        messages.success(request,"Added successfully")
    elif action == "remove":
        order_item.quantity = (order_item.quantity-1)
        messages.success(request,"Deducted successfully")
    

    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()

    return JsonResponse(action + ' complete', safe=False)



@login_required(login_url='tugule:login')
def home(request):
    categories = Category.objects.all()
    

    context={ "categories":categories}

    return render(request,'products/products.html',context)
@login_required(login_url='tugule:login')
def products(request,category_id):
    
    category=Category.objects.get(id=category_id)
    products=Product.objects.filter(category=category)

    context = {'category':category,'products':products,}
    # print(context)
    return render(request,'products/category.html',context)




@login_required(login_url='tugule:login')
def deleteOrder(request,product_id):
    order=OrderItem.objects.get(id=product_id)
    if request.method=='POST':
        order.delete()
        return redirect('products:cart')
    context={"order":order}

    return render(request,'products/delete.html',context)

def checkout_order(request):
    order = Order.objects.get(customer=request.user, complete=False)
    order.complete = True
    order.save()
    messages.success(request,"Order placed successfully")
    return redirect("products:home")

products/templates/products/cart.html
{% extends 'products/base.html' %}
{% load bootstrap5 %}
{% bootstrap_css%}
{% bootstrap_javascript%}
{% block content %}
<style>
    body{
        background-color: rgb(179, 178, 182);
      }
</style>

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <hr>
<div class="container bg-light rounded">
  <table id="cart" class="table table-hover table-condensed">
    <thead>
      <tr>
        <th style="width:50%">Product</th>
        <th style="width:10%">Price</th>
        <th style="width:8%">Quantity</th>
        <th style="width:22%" class="text-center">Subtotal</th>
        <th style="width:10%"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for item in items %}
        <td data-th="Product">
            
          <div class="row p-4">
            <div class="col-sm-2 hidden-xs px-2"><img src="{{item.product.image.url}}" style="height: 80px; width: 80px;" alt="..." class="img-responsive" /></div>
            <div class="col-sm-10">
              <h4 class="nomargin">{{item.product.name}}</h4>
              
            </div>
          </div>
        </td>
        <td data-th="Price">Shs.{{item.product.price}}</td>
        <td data-th="Quantity">
          {{item.quantity}}
        </td>
        <td data-th="Subtotal" class="text-center">Shs.{{item.get_total}}</td>
        <td class="actions" data-th="">
            <div class="d-flex justify-content-between" style="width: 150px;">
                <button data-product="{{item.product.id}}" data-action="add" class="btn btn-info btn-sm update-cart"><i class="fa fa-plus"></i></button>
          <button data-product="{{item.product.id}}" class="btn btn-danger btn-sm update-cart" data-action="remove"><i class="fa fa-minus"></i></button>
          <a class="btn btn-danger justify-self-start " href="{%url 'products:delete_order' item.id%}">Delete</a>
            </div>
            
          
        </td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr class="visible-xs">
        <td class="text-center"><strong>Total items {{order.get_cart_items}}</strong></td>
      </tr>
      <tr>
        <td><a href="{%url 'products:home'%}" class="py-3" style="color: black; text-decoration: none; background-color: rgb(14, 1, 54);"><button   class="fbtn btn-dark text-light"><i class="fa fa-angle-left"></i> Continue Shopping</button></a></td>
        <td colspan="2" class="hidden-xs"></td>
        <td class="hidden-xs text-center"><strong>Total Shs. {{order.get_cart_total}}</strong></td>
        <td><a href="{%url 'products:checkout'%}" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
      </tr>
    </tfoot>
  </table>
</div>
</div>
{% endblock %}

products/templates/products/category.html
{% extends 'products/base.html' %}

{% load bootstrap5 %}
{% bootstrap_css%}
{% bootstrap_javascript%}
{% block content %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
 integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
<style>
    body{
        background-color: rgb(179, 178, 182);
      }
      
  .card {
  position: relative;
  background: transparent;
  width: 300px;
  height: 300px;
  border: none;
}

.card:hover {
  width: 300px;
}

.card .container-image {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: #e7e7e7;
  width: 190px;
  height: 190px;
  display: flexbox;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  border: none;
  border-radius: 50%;
  box-shadow: 0 0 3px 1px #1818183d, 2px 2px 3px #18181865, inset 2px 2px 2px #ffffff;
  transition: all .3s ease-in-out, opacity .3s;
  transition-delay: .6s, 0s;
}

.card:hover .container-image {
  opacity: 0;
  border-radius: 8px;
  transition-delay: 0s, .6s;
}

.card .container-image .image-circle {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 125px;
  height: auto;
  object-fit: contain;
  filter: drop-shadow(2px 2px 2px #1818188a);
  transition: all .3s ease-in-out;
  transition-delay: .4s;
}

.card:hover .container-image .image-circle {
  opacity: 0;
  transition-delay: 0s;
}

.card .content {
  display: flex;
  justify-content: space-between;
  align-items: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: #e7e7e7;
  padding: 20px;
  width: 210px;
  height: 190px;
  cursor: pointer;
  border: none;
  border-radius: 8px;
  box-shadow: 0 0 3px 1px #1818183d, 2px 2px 3px #18181865, inset 2px 2px 2px #ffffff;
  visibility: hidden;
  transition: .3s ease-in-out;
  transition-delay: 0s;
  z-index: 1;
}

.card:hover .content {
  width: 340px;
  height: 230px;
  visibility: visible;
  transition-delay: .5s;
}

.card .content .detail {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  opacity: 0;
  transition: all .3s ease-in-out;
  transition-delay: 0s;
}

.card:hover .content .detail {
  color: #181818;
  opacity: 100%;
  transition: 1s;
  transition-delay: .3s;
}

.card .content .detail span {
  margin-bottom: 5px;
  font-size: 18px;
  font-weight: 800;
}

.card .content .detail button {
  color: rgb(242, 242, 249);
        background-color: rgb(5, 2, 93);

}

.card .content .detail button:hover {
  background: #070400;
}

.card .content .product-image {
  position: relative;
  width: 100%;
  height: 100%;
}

.card .content .product-image .box-image {
  display: flex;
  position: absolute;
  top: 0;
  left: -25%;
  width: 100%;
  height: 115%;
  opacity: 0;
  transform: scale(.5);
  transition: all .5s ease-in-out;
  transition-delay: 0s;
}

.card:hover .content .product-image .box-image {
  top: -25%;
  left: 0;
  opacity: 100%;
  transform: scale(1);
  transition-delay: .3s;
}

.card .content .product-image .box-image .img-product {
  margin: auto;
  width: 7rem;
  height: auto;
}

.fil-shoes1, .fil-shoes2 {
  fill: #333333
}
.row {
    display: flex;
    flex-wrap: wrap;
    margin: 1em;
    padding: 1em;
  }
  .col {
    flex: 1 0 150px;
    margin: 1em;
    min-width: 100px;
    padding: 1em;
  }
</style>

<div class="row d-flex flex-wrap  justify-content-evenly w-100 mx-auto">
  {%if products %}
  {%for product in products%}
  <div class="col-md-4">
    <div class="card ">
      
      
      <div class="container-image d-flex justify-content-center align-content-center">
        <img class="mx-auto w-100 h-100" src="{{product.image.url}}"  alt="{{product.name}}"height="120px"width="120px" style="border-radius: 100%;">
      </div>
      <div class="content d-flex justify-content-between">
        <div class="detail">
          <span>{{product.name}}</span>
          <p>Business: {{product.business_account.name}}</p>
          <p>Price: {{product.price}}</p>
          <!-- {{product.get_average_rating}} -->
          <br>
          <div class="d-flex flex-row justify-content-around">
            <a href="{%url 'tugule:product_details' product.id%}">
              <div class="btn btn-primary">
                Details
              </div>
            </a>
            <button data-product="{{product.id}}" data-action="add" class="update-cart btn btn-primary btn-sm d-flex justify-content-center align-items-center"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
              <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9z"/>
              <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
            </svg></button>
          </div>
          
        </div>
        <div class="product-image">
          <div class="box-image d-flex align-items-center">
            <img class="img" src="{{product.image.url}}"  alt="{{product.name}}"height="120px"width="120px" style="border-radius: 5px;">
            
          </div>
        </div>
      </div>
    </div>
  </div>
  {%endfor%}
  {%else%}
  <h4>No Such  Product Found!</h4>
  {%endif%}
</div>
{%endblock%}

products/templates/products/checkout.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title>Tugule</title>
<link rel="shortcut icon" type="image/png" href="https://image.ibb.co/fOur3b/favicon.png"/>
<style>
body {
  font-family: Arial;
  font-size: 17px;
  padding: 8px;
}

* {
  box-sizing: border-box;
}

.row {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
  margin: 0 -16px;
}

.col-25 {
  -ms-flex: 25%; /* IE10 */
  flex: 25%;
}

.col-50 {
  -ms-flex: 50%; /* IE10 */
  flex: 50%;
}

.col-75 {
  -ms-flex: 75%; /* IE10 */
  flex: 75%;
}

.col-25,
.col-50,
.col-75 {
  padding: 0 16px;
}

.container {
  background-color: #f2f2f2;
  padding: 5px 20px 15px 20px;
  border: 1px solid lightgrey;
  border-radius: 3px;
}

input[type=text] {
  width: 100%;
  margin-bottom: 20px;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 3px;
}

label {
  margin-bottom: 10px;
  display: block;
}

.icon-container {
  margin-bottom: 20px;
  padding: 7px 0;
  font-size: 24px;
}

.btn {
  background-color: #04AA6D;
  color: white;
  padding: 12px;
  margin: 10px 0;
  border: none;
  width: 100%;
  border-radius: 3px;
  cursor: pointer;
  font-size: 17px;
}

.btn:hover {
  background-color: #45a049;
}

a {
  color: #2196F3;
}

hr {
  border: 1px solid lightgrey;
}

span.price {
  float: right;
  color: grey;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other (also change the direction - make the "cart" column go on top) */
@media (max-width: 800px) {
  .row {
    flex-direction: column-reverse;
  }
  .col-25 {
    margin-bottom: 20px;
  }
}
</style>
</head>
<body>


<div class="row">
  <div class="col-75">
    <div class="container">
      <form action="{%url 'products:checkout-order'%}" method="POST">
        {%csrf_token%}
        <div class="row">
          <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
            <input type="text" id="fname" name="firstname" placeholder="John M. Doe">
            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input type="text" id="email" name="email" placeholder="john@example.com">
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="Lumumba Avenue">
            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input type="text" id="city" name="city" placeholder="Kampala">

            <div class="row">
              <div class="col-50">
                <label for="state">District</label>
                <input type="text" id="state" name="state" placeholder="Wakiso">
              </div>
              <div class="col-50">
                <label for="zip">Postal Address</label>
                <input type="text" id="zip" name="zip" placeholder="P.O Box 457">
              </div>
            </div>
          </div>

          <div class="col-50">
            <h3>Payment</h3>
            <label for="fname">Accepted Cards</label>
            <div class="icon-container">
              <i class="fa fa-cc-visa" style="color:navy;"></i>
              <i class="fa fa-cc-amex" style="color:blue;"></i>
              <i class="fa fa-cc-mastercard" style="color:red;"></i>
              <i class="fa fa-cc-discover" style="color:orange;"></i>
            </div>
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="John More Doe">
            <label for="ccnum">Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
            <label for="expmonth">Exp Month</label>
            <input type="text" id="expmonth" name="expmonth" placeholder="September">
            <div class="row">
              <div class="col-50">
                <label for="expyear">Exp Year</label>
                <input type="text" id="expyear" name="expyear" placeholder="2018">
              </div>
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="352">
              </div>
            </div>
          </div>
          
        </div>
        <label>
          <input type="checkbox" checked="checked" name="sameadr"> Save Details
        </label>
        <input type="submit" value="Place Order" class="btn">
      </form>
    </div>
  </div>
  
  </div>
</div>

</body>
</html>

products/templates/products/delete.html
{%load static%}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
 integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<body>
<p>Are you sure you want to delete {{order}}?</p>
<div class ="row">
    <div class="col-md-6">
        <div class="card card-body">
            <form action="{%url 'products:delete_order' order.id%}" method="POST">
                {%csrf_token%}
                <a class="btn btn-warning" href="{%url 'products:cart'%}">Cancel</a>
                <input class="btn btn-danger" type="submit" name="Confirm">
            
            </form>
        </div>
    </div>
</div>

products/templates/products/navbar.html
{%load static%}
<style>
  .hello-msg{
    font-size: 18px;
    margin-right: 20px;
  }
</style>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
 integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg navbar-dark "style=background-color:teal>
  <img  src="{%static 'images/logo.png'%}" alt="" height=70px style="border-radius: 100%;">
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" style=color:black href="{%url 'tugule:home'%}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"style=color:black href="{%url 'tugule:profile'%}">Profile</a>
        </li>
        
        {%if request.user.business_account%}
        <li class="nav-item">
          <a class="nav-link"style=color:black href="{%url 'tugule:business-profile'%}">Business Profile</a>
        </li>
        {%else%}
        <li class="nav-item">
          <a class="nav-link"style=color:black href="{%url 'products:home'%}">Product Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"style=color:black href="{%url 'tugule:create_business'%}">Create Business</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"style=color:black href="{%url 'products:cart'%}"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
          </svg></i></a>
        </li>
        {% endif %}
    
       
      </ul>
    </div>
    <span class="hello-msg">Hello, 
      {% if profile.name == 'user' %}
      {{request.user.username}}
      {% else %}
      {{request.user.profile.name}}
      
      {% endif %}</span>
    
      <span><a href="{%url 'tugule:logout'%}" class="btn btn-danger btn-sm">Log out</a></span> 
    </a>
    
  </nav>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

products/templates/products/products.html
{% extends 'products/base.html' %}

{% load bootstrap5 %}
{% bootstrap_css%}
{% bootstrap_javascript%}
{% block content %}  
<style>
    body{
        background-color: rgb(179, 178, 182);
      }
.card {
  width: 100%;
  max-width: 300px;
  min-width: 200px;
  height: 250px;
  background-color: #292929;
  margin: 10px;
  border-radius: 10px;
  box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.359);
  border: 2px solid rgba(7, 7, 7, 0.12);
  font-size: 16px;
  transition: all 0.3s ease;
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  cursor: pointer;
  font-family: 'Poppins', sans-serif;
}

.icon {
  margin: 0 auto;
  width: 100%;
  height: 80px;
  max-width: 80px;
  background: linear-gradient(90deg, #7eaaff 0%, #ff48fb 40%, rgba(0, 0, 0, 0.28) 60%);
  border-radius: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  transition: all 0.8s ease;
  background-position: 0px;
  background-size: 200px;
}

.icon svg {
  fill: white;
}

.card .title {
  width: 100%;
  margin: 0;
  text-align: center;
  margin-top: 30px;
  color: white;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 4px;
}

.card .text {
  width: 80%;
  margin: 0 auto;
  font-size: 13px;
  text-align: center;
  margin-top: 20px;
  color: white;
  font-weight: 200;
  letter-spacing: 2px;
  opacity: 0;
  max-height: 0;
  transition: all 0.3s ease;
}

.card:hover {
  height: 270px;
}

.card:hover .text {
  transition: all 0.3s ease;
  opacity: 1;
  max-height: 40px;
}

.card:hover .icon {
  background-position: -120px;
  transition: all 0.3s ease;
}

.card:hover .icon svg path {
  fill: url('#gradientColor');
  transition: all 0.3s ease;
}
</style>

<div class="cards d-flex flex-wrap justify-content-center">
  {% for category in categories %}

  <a href="{% url 'products:category' category.id  %}" style="text-decoration: none;">
    <div class="card ">

      <div class="icon">
        <img src="{{category.image.url}}" alt="{{category.name}}"height="100%"width="100%" style="border-radius: 100px;">
          
      </div>
      <p class="title">{{category.name|title}}</p>
      <p class="text">Explore Our  Collection of Products Today!.</p>
    </div>
</a>

{% endfor %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>


{%endblock%}